server:
  port: 80
  #Eureka配置
eureka:
  client:
    register-with-eureka: false
    service-url: # 从三个注册中心中随机取一个去访问
      defaultZone:
        ervice-url: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/