server:
  port: 8001
#mybatis配置
mybatis:
  type-aliases-package: com.springcloud.pojo
  config-location: classpath:mybatis/mybatis_config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring配置


spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://codekitty.cn:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: lihaiyang

eureka:
  client:
    service-url:  #监控页面
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
    instance:
      instance-id: springcloud-provider-dept:8001

info:
  app.name: springcloud-DeptProvider
  company.name: codekitty.cn

